### ISSUE TITLE
License issue: BSD-3-Clause or Apache-2.0?

### ISSUE THREAD

**Issue by ffontaine** [AsteroidOS/brcm-patchram-plus#2]
Could you clarify the license of brcm-patchram-plus? COPYING is specifying BSD-3-Clause but the only source file (src/main.c) has an Apache-2.0 header.

**Comment by FlorentRevest** [comment]
This is an interesting question...
Looking at the "upstream" brcm-patchram-plus, only the main.c file is distributed, under the Apache-2.0 license. The tool itself is therefore most likely distributed under Apache-2.0 https://android.googlesource.com/platform/system/bluetooth/+/master/brcm_patchram_plus
However, when this tool was introduced to the repository this repository is a fork of, autotools build scripts were also added at the same time: https://github.com/AsteroidOS/brcm-patchram-plus/commit/a8dd68fe306bb25971126224878ab0d637e4ae87 and it looks like those build scripts have been copied from another part of the repository which was under BSD-3-Clause.
I would therefore conclude that the tool itself is under Apache-2.0 but for some weird historic reasons, the autotools scripts are under BSD-3... Feel free to PR this repository to clarify that situation or just consider the Apache-2.0 license used in the code (which is the only part that you actually redistribute)

**Comment by ffontaine** [comment]
OK thanks a lot for this clarification, I'll send a PR.
